# Generated by Django 2.2.7 on 2019-11-30 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(choices=[('sahabiness', 'Sahabiness'), ('problem-solving', 'Problem solving'), ('execution', 'Execution'), ('thought-leadership', 'Thought leadership'), ('leadership', 'Leadership'), ('presence', 'Presence')], max_length=20)),
                ('rating', models.IntegerField(choices=[(1, 'Needs improvement'), (2, 'Consistently meets expectations'), (3, 'Exceeds expectations'), (4, 'Strongly exceeds expectations'), (5, 'Superb')])),
                ('description', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
