# Generated by Django 3.0 on 2019-12-09 14:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personreview',
            name='execution_comment',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='execution_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'STRONGLY_EXCEEDS_EXPECTATIONS'), (5, 'SUPERB')], null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='leadership_comment',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='leadership_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'STRONGLY_EXCEEDS_EXPECTATIONS'), (5, 'SUPERB')], null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='presence_comment',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='presence_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'STRONGLY_EXCEEDS_EXPECTATIONS'), (5, 'SUPERB')], null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='problem_solving_comment',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='problem_solving_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'STRONGLY_EXCEEDS_EXPECTATIONS'), (5, 'SUPERB')], null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='sahabiness_comment',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='sahabiness_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'STRONGLY_EXCEEDS_EXPECTATIONS'), (5, 'SUPERB')], null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='strengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=280), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='thought_leadership_comment',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='thought_leadership_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'STRONGLY_EXCEEDS_EXPECTATIONS'), (5, 'SUPERB')], null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='weaknesses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=280), blank=True, null=True, size=3),
        ),
    ]
