# Generated by Django 3.0 on 2019-12-16 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191214_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personreview',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectreview',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='personreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
