# Generated by Django 3.0 on 2019-12-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191216_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.IntegerField(choices=[(1, 'SELF_REVIEW'), (2, 'PEER_REVIEW'), (3, 'MANAGER_REVIEW'), (4, 'RESULTS')])),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
    ]
