# Generated by Django 3.0 on 2020-01-01 07:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personreview',
            name='strengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='weaknesses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=3),
        ),
    ]
