# Generated by Django 3.0 on 2020-01-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200101_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='personreview',
            name='final_submit',
            field=models.BooleanField(default=False),
        ),
    ]
