# Generated by Django 3.0 on 2020-01-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_change_evaluation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='login_background_image',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
