# Generated by Django 3.0 on 2020-01-21 13:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200114_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personreview',
            name='strengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=280), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='weaknesses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=280), blank=True, null=True, size=3),
        ),
    ]
