# Generated by Django 3.0 on 2020-01-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200121_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='phase',
            field=models.IntegerField(choices=[(1, 'SELF_REVIEW'), (2, 'PEER_REVIEW'), (3, 'MANAGER_REVIEW'), (4, 'RESULTS'), (5, 'IDLE')]),
        ),
    ]
