# Generated by Django 3.0 on 2020-01-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200126_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='idle_page_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
