# Generated by Django 3.0 on 2020-02-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_settings_idle_page_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personreview',
            name='final_submit',
        ),
    ]
