# Generated by Django 3.0 on 2020-04-25 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_personreview_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personreview',
            name='execution_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='leadership_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='presence_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='problem_solving_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='sahabiness_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='strengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='thought_leadership_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personreview',
            name='weaknesses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='projectcomment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
