# Generated by Django 3.0 on 2020-10-01 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_auto_20200425_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVEMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'SUPERB')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project_review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ProjectReview')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerPersonReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sahabiness_rating', models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVEMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'SUPERB')], null=True)),
                ('problem_solving_rating', models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVEMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'SUPERB')], null=True)),
                ('execution_rating', models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVEMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'SUPERB')], null=True)),
                ('thought_leadership_rating', models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVEMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'SUPERB')], null=True)),
                ('leadership_rating', models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVEMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'SUPERB')], null=True)),
                ('presence_rating', models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVEMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'SUPERB')], null=True)),
                ('overall_rating', models.IntegerField(blank=True, choices=[(1, 'NEEDS_IMPROVEMENT'), (2, 'MEETS_EXPECTATIONS'), (3, 'EXCEEDS_EXPECTATIONS'), (4, 'SUPERB')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_manager_person_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_person_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
