# Generated by Django 3.1.2 on 2020-10-06 15:45

from django.db import migrations, models


def fill_null_phases(app, schema_editor):
    Settings = app.get_model('core', 'Settings')
    for settings in Settings.objects.all():
        settings.phase = 1
        settings.save(update_fields=['phase'])


class Migration(migrations.Migration):
    """
    This migration was added manually to ensure reversablity.
    """

    dependencies = [
        ('core', '0018_managerpersonreview_managerprojectcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='phase',
            field=models.IntegerField(choices=[(1, 'SELF_REVIEW'), (2, 'PEER_REVIEW'), (3, 'MANAGER_REVIEW'), (4, 'RESULTS'), (5, 'IDLE')], null=True),
        ),
        migrations.RunPython(migrations.RunPython.noop, fill_null_phases)
    ]
