# Generated by Django 3.1.2 on 2020-10-06 13:12

from django.db import migrations


def set_active_round(apps, schema_editor):
    Round = apps.get_model("core", "Round")
    Settings = apps.get_model("core", "Settings")
    last_round = Round.objects.all().last()
    if last_round is None:
        last_round = Round(title='Default Round', phase=1)
        last_round.save()
    for settings in Settings.objects.filter(active_round__isnull=True):
        settings.active_round = last_round
        settings.save(update_fields=['active_round'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201006_1256'),
    ]

    operations = [
        migrations.RunPython(set_active_round)
    ]
