# Generated by Django 3.1.2 on 2020-10-06 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_auto_20201006_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phase',
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('phase', models.IntegerField(choices=[(1, 'SELF_REVIEW'), (2, 'PEER_REVIEW'), (3, 'MANAGER_REVIEW'), (4, 'RESULTS'), (5, 'IDLE')])),
                ('start_text_self_review', models.TextField(blank=True, null=True)),
                ('start_text_peer_review', models.TextField(blank=True, null=True)),
                ('start_text_manager_review', models.TextField(blank=True, null=True)),
                ('start_text_results', models.TextField(blank=True, null=True)),
                ('start_text_idle', models.TextField(blank=True, null=True)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(to='core.Project')),
            ],
        ),
        migrations.AddField(
            model_name='managerpersonreview',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.round'),
        ),
        migrations.AddField(
            model_name='personreview',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.round'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.round'),
        ),
        migrations.AddField(
            model_name='settings',
            name='active_round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.round'),
        ),
    ]
