# Generated by Django 3.1.2 on 2020-10-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_set_settings_current_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='active_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.round'),
        ),
    ]
