# Generated by Django 3.1.2 on 2020-10-06 18:12

from django.db import migrations


def set_active_round(apps, schema_editor):
    Round = apps.get_model('core', 'Round')
    last_round = Round.objects.all().last()
    if last_round is None:
        last_round = Round(title='Default Round', phase=1)
        last_round.save()

    Settings = apps.get_model('core', 'Settings')
    for settings in Settings.objects.filter(active_round__isnull=True):
        settings.active_round = last_round
        settings.save(update_fields=['active_round'])

    model_names = ['ProjectReview', 'PersonReview', 'ManagerPersonReview']
    for model_name in model_names:
        Model = apps.get_model('core', model_name)
        for obj in Model.objects.filter(round__isnull=True):
            obj.round = last_round
            obj.save(update_fields=['round'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201006_1810'),
    ]

    operations = [
        migrations.RunPython(set_active_round, migrations.RunPython.noop)
    ]
