# Generated by Django 3.1.2 on 2020-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='manager_overall_review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
