# Generated by Django 3.1.2 on 2020-12-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_round_manager_overall_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerpersonreview',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='managerprojectcomment',
            name='manager',
        ),
    ]
