# Generated by Django 3.1.2 on 2021-11-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20211031_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreview',
            name='project_name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
