# Generated by Django 3.1.2 on 2021-11-14 16:23

from django.db import migrations


def set_project_name(apps, schema_editor):
    ProjectReview = apps.get_model('core', 'ProjectReview')
    for project_review in ProjectReview.objects.all():
        project_review.project_name = project_review.project.name
        project_review.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_projectreview_project_name'),
    ]

    operations = [
        migrations.RunPython(set_project_name, migrations.RunPython.noop)
    ]
