# Generated by Django 3.1.2 on 2021-11-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_set_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreview',
            name='project',
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='project_name',
            field=models.CharField(max_length=512),
        ),
    ]
