# Generated by Django 3.1.2 on 2021-11-16 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_auto_20211114_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='projects',
        ),
        migrations.AlterField(
            model_name='projectreview',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='project_reviews_to_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='round',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
