# Generated by Django 3.1.2 on 2022-06-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20211118_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreview',
            name='consulted_with_manager',
            field=models.BooleanField(default=False),
        ),
    ]
