# Generated by Django 3.1.2 on 2022-06-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220625_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='max_project_reviews',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='round',
            name='max_reviewers',
            field=models.IntegerField(default=5),
        ),
    ]
