# Generated by Django 3.1.2 on 2022-06-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220625_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='max_reviwers',
            new_name='max_reviewers',
        ),
    ]
