# Generated by Django 3.1.2 on 2022-07-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_round_reviewers_are_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='manager_review_project_fields',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='peer_review_project_fields',
            field=models.TextField(default='[{"key": "text", "label": "شواهد و بازخورد"}]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='private_manager_review_project_fields',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='self_review_project_fields',
            field=models.TextField(default='[{"key": "text", "label": "توضیح فعالیت"}]'),
            preserve_default=False,
        ),
    ]
