# Generated by Django 3.1.2 on 2022-07-05 11:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_round_reviewers_are_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.IntegerField(choices=[(1, 'TEXT'), (2, 'CHECKBOX_MULTIPLE')])),
                ('label', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('private_answer_to_peer_reviewers', models.BooleanField(default=False)),
                ('private_answer_to_reviewee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.question')),
            ],
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='answers',
            field=models.ManyToManyField(blank=True, to='core.Answer'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='answers',
            field=models.ManyToManyField(blank=True, to='core.Answer'),
        ),
        migrations.AddField(
            model_name='round',
            name='manager_review_project_questions',
            field=models.ManyToManyField(blank=True, related_name='manager_reviews_asked', to='core.Question'),
        ),
        migrations.AddField(
            model_name='round',
            name='peer_review_project_questions',
            field=models.ManyToManyField(blank=True, related_name='peer_reviews_asked', to='core.Question'),
        ),
        migrations.AddField(
            model_name='round',
            name='self_review_project_questions',
            field=models.ManyToManyField(blank=True, related_name='self_reviews_asked', to='core.Question'),
        ),
    ]
