# Generated by Django 3.1.2 on 2022-07-03 15:27
import json

from django.db import migrations


def jsoinze_review_texts(apps, schema_editor):
    ProjectReview = apps.get_model('core', 'ProjectReview')
    for project_review in ProjectReview.objects.all():
        project_review.text = json.dumps({'text': project_review.text})
        project_review.save()

    ProjectComment = apps.get_model('core', 'ProjectComment')
    for project_comment in ProjectComment.objects.all():
        project_comment.text = json.dumps({'text': project_comment.text})
        project_comment.save()


def flatten_review_texts(apps, schema_editor):
    ProjectReview = apps.get_model('core', 'ProjectReview')
    for project_review in ProjectReview.objects.all():
        project_review.text = json.loads(project_review.text)['text']
        project_review.save()

    ProjectComment = apps.get_model('core', 'ProjectComment')
    for project_comment in ProjectComment.objects.all():
        project_comment.text = json.loads(project_comment.text)['text']
        project_comment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20220703_1519'),
    ]

    operations = [
        migrations.RunPython(jsoinze_review_texts, flatten_review_texts)
    ]
