# Generated by Django 3.1.2 on 2022-07-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20220705_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='self_review_execution_help_modal_text',
        ),
        migrations.RemoveField(
            model_name='round',
            name='self_review_leadership_help_modal_text',
        ),
        migrations.RemoveField(
            model_name='round',
            name='self_review_presence_help_modal_text',
        ),
        migrations.RemoveField(
            model_name='round',
            name='self_review_problem_solving_help_modal_text',
        ),
        migrations.RemoveField(
            model_name='round',
            name='self_review_project_review_help_modal_text',
        ),
        migrations.RemoveField(
            model_name='round',
            name='self_review_sahabiness_help_modal_text',
        ),
        migrations.RemoveField(
            model_name='round',
            name='self_review_thought_leadership_help_modal_text',
        ),
    ]
