# Generated by Django 3.1.2 on 2022-07-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20220725_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='max_choices',
            field=models.IntegerField(default=-1),
        ),
    ]
