# Generated by Django 3.1.2 on 2022-07-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20220726_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprojectcomment',
            name='answers',
            field=models.ManyToManyField(blank=True, to='core.Answer'),
        ),
    ]
