# Generated by Django 3.1.2 on 2022-07-28 11:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_managerprojectcomment_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerpersonreview',
            name='strengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=3),
        ),
        migrations.AddField(
            model_name='managerpersonreview',
            name='weaknesses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=3),
        ),
    ]
