# Generated by Django 3.1.2 on 2022-07-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20220728_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Required for completion in reports'),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_choices',
            field=models.IntegerField(default=-1, help_text='For no limit, enter -1'),
        ),
    ]
