# Generated by Django 3.0 on 2020-01-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191216_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
    ]
