# Generated by Django 3.1.2 on 2020-10-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201006_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_started',
        ),
    ]
