# Generated by Django 3.1.2 on 2020-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_has_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ranking1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ranking2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
